### ISSUE TITLE
A question: how to calculate the grain number based on the PFC simulation results?

### ISSUE THREAD

**Issue by abhpc** [petenez/pfc#2]
First, thank you for your wonderful work, and your work is very important for modeling the polycrystalline graphene and other 2D materials.
However, I have a question: how to calculate the grain number based on the PFC simulation results? The average grain size is very important for futher studying.

**Comment by petenez** [comment]
Thanks! Glad you like it.

In Hirvonen et al., Physical Review Materials 2018 ( https://arxiv.org/pdf/1806.00700.pdf ), I wrote some code for this purpose (and its workings are described quite well in that paper too). However this code is definitely not ready for publication and I'm afraid it might never be as I don't work with PFC and 2D materials anymore.

One approach you could consider is to use ImageJ software - just google something like "imagej grain size" and there seem to be quite many hits. You would need to filter out the atomic-level structure first though. I'd recommend using my tools in this repo to calculate the "deformation field" of your system; see the paper above. I'd imagine that if you'd plot the deformation field then that should work pretty well as the input for ImageJ analysis.

Of course if you don't have too many grains to count, you could just use the grid method where you place a grid on top of your microstructure, follow each line and count the grain boundaries that they cross. There seem to be quite many Google hits for the grid method in determining the grain size of microstructures also.

You could also count the number of grains and hence the average grain sizes for a handful of small well-relaxed systems and you could then consider larger well-relaxed systems and estimate their grain sizes from the scaling of their formation energy. Our papers Hirvonen et al., Physical Review B 2016 ( https://arxiv.org/pdf/1605.03765.pdf ) and Hirvonen et al., Scientific Reports 2017 ( https://www.nature.com/articles/s41598-017-04852-w ) should give a pretty good idea how the formation energy of 2D systems scales with the average grain size.

**Comment by abhpc** [comment]
Thank you for your kind response. I have developed a tool to estimate the average grain size using line cut method (https://github.com/abhpc/linecut-polycrystalline-graphene).
A more question: would you give the units of variables listed below (alpha to delta) for the previous two-step PFC modeling of polycrystalline graphene:
```
# model parameters
#	alpha	beta	gamma	delta	c
M	-0.15	1.0		0.87	1.0		0
#	F = int dr (psi/2*(alpha + beta*(1 + nabla^2)^2)*psi + gamma*psi^3/3 + delta*psi^4/4)
#	c = 1: conserved (diffusive) dynamics: dpsi/dt = nabla^2 dF/dpsi
#	c = 0: nonconserved (gradient descent) dynamics: dpsi/dt = -dF/dpsi
```
I recognise that the free energy is calculated based on Eq. (1)  in your paper [Physical Review B 94, 035414 (2016)](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.94.035414). However, I do not know the units used in your programs. Would you please tell me their units? Thank you.
