### ISSUE TITLE
Question: the parameter units.

### ISSUE THREAD

**Issue by abhpc** [petenez/pfc#3]
Thank you for your previous kind response. I have developed a tool to estimate the average grain size using line cut method (https://github.com/abhpc/linecut-polycrystalline-graphene).
A more question: would you give the units of variables listed below (alpha to delta) for the previous two-step PFC modeling of polycrystalline graphene:
```
# model parameters
#	alpha	beta	gamma	delta	c
M	-0.15	1.0		0.87	1.0		0
#	F = int dr (psi/2*(alpha + beta*(1 + nabla^2)^2)*psi + gamma*psi^3/3 + delta*psi^4/4)
#	c = 1: conserved (diffusive) dynamics: dpsi/dt = nabla^2 dF/dpsi
#	c = 0: nonconserved (gradient descent) dynamics: dpsi/dt = -dF/dpsi
```
I recognise that the free energy is calculated based on Eq. (1)  in your paper [Physical Review B 94, 035414 (2016)](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.94.035414). However, I do not know the units used in your programs. Would you please tell me their units? Thank you.

**Comment by petenez** [comment]
The model parameters are dimensionless, i.e., they don't have units. You would need to follow a similar procedure to what we did in that paper: we fitted the energy scale to grain boundary energy from DFT calculations. Of course you could also fit the elastic modulus to an experimental value. If you use the same model and parameters as we did in that paper then you should be able to use the same energy scaling coefficient (given in the paper) as we did to convert your energies etc. to real units.
